# Generated by Django 3.0.4 on 2020-03-26 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('numero_product', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
                ('preco', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'permissions': (('geral_products_visualizar', 'Pode visualizar Products'), ('geral_products_editar', 'Pode visualizar e editar Products')),
                'default_permissions': (),
            },
        ),
    ]
