# Generated by Django 3.0.4 on 2020-05-08 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200405_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('new_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Product')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
                'permissions': (('geral_offer_visualizar', 'Pode visualizar Offer'), ('geral_offer_editar', 'Pode visualizar e editar Offer')),
                'default_permissions': (),
            },
        ),
    ]
