# Generated by Django 3.0.4 on 2020-04-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_remove_category_owner'),
        ('produto', '0002_auto_20200326_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numero_product',
            new_name='number_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='preco',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantidade',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ManyToManyField(to='categoria.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
