# Generated by Django 3.0.4 on 2020-05-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
