# Generated by Django 3.0.4 on 2020-04-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20200402_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
