# Generated by Django 3.0.6 on 2020-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20200611_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='peso',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade',
            field=models.IntegerField(default=1),
        ),
    ]
