# Generated by Django 3.0.4 on 2020-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_remove_category_owner'),
        ('produto', '0005_auto_20200402_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='categoria.Category'),
        ),
    ]
