# Generated by Django 3.0.6 on 2020-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20200615_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_bought',
            field=models.IntegerField(default=0),
        ),
    ]
