# Generated by Django 3.0.4 on 2020-04-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20200402_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoria',
            new_name='categories',
        ),
    ]
