# Generated by Django 3.0.4 on 2020-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('base_64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'permissions': (('geral_images_visualizar', 'Pode visualizar Images'), ('geral_images_editar', 'Pode visualizar e editar Images')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Carrosel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ManyToManyField(to='carrosel.Image')),
            ],
            options={
                'verbose_name': 'Carrosel',
                'verbose_name_plural': 'Carrosel',
                'permissions': (('geral_carrosel_visualizar', 'Pode visualizar Carrosel'), ('geral_carrosel_editar', 'Pode visualizar e editar Carrosel')),
                'default_permissions': (),
            },
        ),
    ]
