# Generated by Django 3.0.4 on 2020-05-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrosel', '0002_auto_20200508_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
