# Generated by Django 3.0.4 on 2020-04-03 03:46

import core.accounts.roles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=core.accounts.roles.utils.get_default_role, to='accounts.Role'),
        ),
    ]
