# Generated by Django 3.0.4 on 2020-05-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_offer'),
        ('purchases', '0003_auto_20200509_1603'),
        ('accounts', '0005_auto_20200509_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cart',
            field=models.ManyToManyField(null=True, related_name='carrinho', to='purchases.ItemProduct'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='favoritos', to='produto.Product'),
        ),
    ]
