# Generated by Django 3.0.4 on 2020-05-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_offer'),
        ('accounts', '0005_auto_20200509_1507'),
        ('purchases', '0002_auto_20200509_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProduct',
            new_name='ItemProduct',
        ),
    ]
