# Generated by Django 3.0.6 on 2020-06-15 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0003_auto_20200509_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Cliente', to=settings.AUTH_USER_MODEL)),
                ('purchases', models.ManyToManyField(to='purchases.ItemProduct')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'permissions': (('geral_orders_visualizar', 'Pode visualizar Orders'), ('geral_orders_editar', 'Pode visualizar e editar Orders')),
                'default_permissions': (),
            },
        ),
    ]
