# Generated by Django 3.0.4 on 2020-04-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
